### ISSUE TITLE
Adding a CHANGLOG.md / versioning.

### ISSUE THREAD

**Issue by LordNoteworthy** [sheredom/hashmap.h#22]
Hello @sheredom 

Wondering if it makes sense to add a changelog to keep track of changes happening on this project.

As I am using `hashmap.h` on my projects, I wish I can have a look quickly at the CHANGELOG file and see weather I require an update in case of a critical bug fix. That implies you need to probably start versioning this project.

Cheers.

**Comment by LordNoteworthy** [comment]
Worth checking: https://keepachangelog.com/en/1.0.0/

**Comment by sheredom** [comment]
First of all - thanks for using my library!

In general I'd always advise you keep to the latest with all my C libraries - I try and keep them all binary forward compatible.

I do like the idea of a changelog, the problem is that I'd then have to start properly versioning my library and honestly... that's a lot of work for a personal project I maintain for the joy of it! Hope you understand!
